### ISSUE TITLE
Mentioning protractor under "Testing" paragraph

### ISSUE THREAD

**Issue by alecxe** [johnpapa/angular-styleguide#344]
I'm not sure whether it fits the style guide, but would it be a good idea to cover end-to-end tests using `protractor` in the [Testing](https://github.com/johnpapa/angular-styleguide#testing) section? 

Thanks.

Feel free to close if it does not make sense.

**Comment by johnpapa** [comment]
Its a good tool. A short mention is a good idea.

**Comment by ciwchris** [comment]
It brings up some good questions. Like, where should the test files reside? Should they be included next to each feature, and so be part of the [Folders-by-Feature Structure](https://github.com/johnpapa/angular-styleguide#style-y152). Or should they be placed within their own folder away from the feature? It would seem nice to place the tests next to each feature, but then care must be taken in determining which test files are Karma tests and which are Protractors tests and run them appropriately, since both follow the naming convention of `spec.js`.

**Comment by wardbell** [comment]
As with unit tests I want my protractor tests next to the feature **if they are narrowly focused on that feature**. 

That isn't always the case. End-to-end (E2E) tests are typically high-level, sweeping integration tests that explore broader questions than the working of a particular component. In that case, I like them in a separate test folder.

But sometimes they are feature specific and I'd like to see them side-by-side with the feature.

Regardless, I always **distinguish protractor/E2E tests by name**.  An approach I favor is to end the test file name with "e2e-spec.js".  This is easily distinguishable from just plain "spec.js".

**Comment by zachlysobey** [comment]
I agree that (karma) unit tests are best to have right in the folder with
the feature. The only time this gets a bit frustrating is when I want to
add one or more test resources as their own files supporting a .spec.js
(Mocks, Fakes, Stubs, helpers). This tends to clutter the feature's
directory. In these cases, I'm tempted to put a test/ directory in the
feature folder for this stuff.

Personally I keep *all* my e2e (protractor) tests in a single place rather
than along-side the feature. While they *are *frequently specific to a
feature, they *do* require the whole app to load and as such I feel that
they really belong at the top level. A possible exception (sort of) is
actually creating a separate test-html app loading a single component in
isolation. I don't do this, but the idea is appealing and would make me
feel better about putting this code along-side the feature.

**Comment by ciwchris** [comment]
My current approach is using "unit.js" for Karma unit tests and "spec.js" for e2e tests. If the test is specific to a feature then it lives in the feature folder, otherwise it is at the root of the app. However, I do use [Page Objects|http://angular.github.io/protractor/#/page-objects] and they live in a test folder outside of the app. This seems to work for me, but is contrary to standard naming. Perhaps I should consider placing feature tests next to the Page Object associated to the feature and all other e2e tests in the root of the test folder. Something to consider.

@zachlysobey creating a separate app for loading a single component in isolation would be ideal, although my first impression is that it will require more work than what I want to put into it.

**Comment by johnpapa** [comment]
good stuff here, but nothing to really add to the "style guide". mostly tips, which is not this guide
