### ISSUE TITLE
Factory vs Service

### ISSUE THREAD

**Issue by patrick-fls** [johnpapa/angular-styleguide#39]
I know the subject has been beaten to death, and I might be thick. 
I've read this http://stackoverflow.com/questions/13762228/confused-about-service-vs-factory/13763886#13763886 and this http://stackoverflow.com/a/15666049

I still don't understand in which situation you should use one instead of the other. Since both returning a singleton, why not just pick the one you prefer (either Factory or Service)  and exclusively use that one?

Why did the angularjs team feel it was necessary to support both ways?

**Comment by localpcguy** [comment]
This blog post, [service vs factory once and for all](http://blog.thoughtram.io/angular/2015/07/07/service-vs-factory-once-and-for-all.html), makes the argument that services should be used over factories because they are constructors, and so can be replaced by ES6 classes in the future. Valid argument for updating the [Services](https://github.com/johnpapa/angular-styleguide#services) section to recommend Services rather than Factories?

I wasn't totally convinced, as I'm not a huge fan of ES6 classes, but I wanted to get other opinions.

**Comment by gkalpak** [comment]
Just because ES6 has classes, people tend to overlook it also has...functions.

Services are indeed constructor functions and factories are not constructor functions.
Services can indeed be replaced by ES6 classes (which is probably a good idea) and factories cannot (and nor should they).
There are places where services and more suitable and there are places where factories are more suitable (that's why the Angular team included both helpers in the first place).
And while it's true that in most cases services are more appropriate and that people tend to overuse factories, there are valid usecases where a factory makes most sense.

So, regardless of ES6, one should use factories in (the few) cases where thay are more appropriate and use services in the rest (constants, values and providers aside).
If one decides to move to ES6, they could/should replace service constructor functions with classes. (And while this is a good practice in itself, it is hardly a valid argument for preferring services over factories).

<sub>Just my 2 cents...</sub>

**Comment by localpcguy** [comment]
I agree with just about everything you said. Given that, should the [Services](https://github.com/johnpapa/angular-styleguide#services) section be updated to say that services should be preferred for consistency, only using Factories as needed (currently that section recommends using Factories primarily to keep things consistent).

**Comment by gkalpak** [comment]
Well, it's @johnpapa's style-guide, not ours (and I think he prefers factories :smiley:).

**Comment by dimkk** [comment]
+1 to gklpak and localpcguy

Services should be preferred for consistency, only using Factories as needed

**Comment by wardbell** [comment]
Factories are richer than services because you can do anything a service can do AND you can create instance captures.

Hard to do that (but not impossible) with service constructors and perhaps impossible with ES6 and Typescript classes. That's why we favored factories.

However, with the future of Ng2 heavily favoring classes (and ctors when writing in ES5), it may be time to rethink our preference .. and/or convince the Ng team to rethink THEIR guidance.

Lets see what John has to say.

**Comment by gkalpak** [comment]
> Factories are richer than services [...] That's why we favored factories.

Ng2 stuff aside, this sounds contradictory to me. Saying _"factories are richer"_ is another way of saying _"services are simpler and cover most usecases (but factories are necessary in few cases)"_. So, it would make more sense (imo) to use the simpler alternative when possible (falling back to the richer option when necessary).
Providers are even richer than factories, I wouldn't expect one to use providers everywhere for consistency though :wink:

(What I am trying to say is that (regardless of ng2/ES6) we should use the simpler tool that gets the job done and rely on more powerful/complex tools only when necessary.)

--
<sub>That said, I realize that factories are in fact only slightly more complex, so one might choose to make the trade-of, sacrifizing a little chuck of simplicity for a little chuck of consistency.</sub>

**Comment by wardbell** [comment]
I see your point but disagree.

 Let me clarify.  When I said factories are richer I meant that they are richer for free.

Services are not simpler than factories. Factories are as easy to write and read as services. You would have a hard time I think demonstrating that services are easier in any respect other than that they have the better name.

And yet factories can do something valuable to the daily programmer that services/classes cannot: they support captures (private variables).  That is no small benefit and the cost is zero. Rather than have two ways to do the same thing, we picked the better way, factories.

Providers are another matter. Services and factories are functionally the same. Providers add a new dimension of capability that neither services nor factories can supply: configurability.

OTOH providers are considerably messier than either factories or services. They have a required $get. They participate in both the config phase and the run phase. They are harder to test. And they're going away in Ng2.

I avoid providers when at all possible and never use them when a service or factory would do. Therefore, they don't belong in this discussion.

The only reason I can think of to prefer service to factory is the trend in Ng2. That may be reason enough.

I want.to hear what John thinks be for changing our preference for factories.

**Comment by johnpapa** [comment]
I'll keep it short.

Factories are cleaner and easier and slightly more featured in Angular 1.x, for all the reasons Ward explained. Services are simply ctor's which makes them more aligned with Angular 2. I rarely ever need anything that is a difference between the 2, but I chose factories for angular 1.x as they were easier to read and write, IMO (and for consistency I chose 1).

Migrating to Angular 2 from a factory or a service is trivial. So **I would not rewrite any code in Angular 1.x from a factory to a service**. Why? Because it is trivial to migrate to a Angular 2 service. However, for new projects I am writing code as services and not factories. Why? Simply to keep the mindset of how Angular 2 works. 

I will be updating the guide, and I am interested in hearing your thoughts on your experiences.

**Comment by gkalpak** [comment]
> And yet factories can do something valuable to the daily programmer that services/classes cannot: they support captures (private variables).

?! I probably miss something, because my Angular services can have private variables too :P
@wardbell, you are probably referring to cases where functions on the prototype chain would like to access _private_ variables. Note that (usually) only **one** instance of a service is created, so there is no need to and (imo) little benefit in assigning functions to the prototype.

Other than that, there is nothing more to add (that hasn't already be said).
The difference is marginal imo, so using factories where a service could have worked as well, introduces a very minor and acceptable overhead. As so many things, in the end of the day it just a matter of taste (as long as you are consistent with your choice).

As for my experience, I used to use factories everywhere (I even wondered why they introduced the `service` helper anyway), but at some point I switched to services whereever possible. Now I am falling back to factories or providers only when necessary and in practice I have found out that my needs for factories are very small (even smaller than that for providers).

---
In case anyone is curious, this is how I structure my services nowadays.
(I only include the necessary "sections" in each service - most of the times it is just the _private variables_, _public functions_ and _functions definitions_.) 

```js
function SomeService() {
  // Constants
  var SOME_CONSTANT = ...;

  // Variables - Private
  var self = this;
  var somePrivateVar1 = ...;
  var somePrivateVar2 = ...;

  // Variables - Public
  self.somePublicVar1 = ...;
  self.somePublicVar2 = ...;

  // Functions - Public
  self.somePublicFn1 = somePublicFn1;
  self.somePublicFn2 = somePublicFn2;

  // Initialization
  _initialize();

  // Functions - Definitions
  function _initialize() {...}

  function somePublicFn1() {...}

  function somePublicFn2() {...}
}
```

---
<sub>Hm...this was supposed to be a tiny comment...what happened ???</sub>

**Comment by gkalpak** [comment]
Oh, btw, I definitely do not suggest one should and change all factories to services wherever possible in an existing app.

Thx @wardbell and @johnpapa for sharing your insights !

**Comment by wardbell** [comment]
@gkalpak - my private/captures complaint should have been confined to classes ... which I have on the brain recently. Thanks for reminding me that ES5 ctors are unconstrained in that respect.

**Comment by johnpapa** [comment]
@gkalpak I do something similar with services:

```javascript
function DataService() {
  var svc = this;
  var someValue = 1;

  svc.saveCustomers = saveCustomers;
  svc.getCustomers = getCustomers;

  activate();

  ////////////////
  function activate() { }

  function saveCustomers() { }

  function getCustomers() { }
}
```

**Comment by gkalpak** [comment]
Well, obviously many of my code styles have been influenced by a style-guide by some @johnpapa guy :laughing:

**Comment by dballesteros7** [comment]
@johnpapa Could you include that latter example for services, even though it's similar to the one for controllers and one can easily deduce it, it would make the guide clearer.
