### ISSUE TITLE
Controller as 'vm'

### ISSUE THREAD

**Issue by strangfeld** [johnpapa/angular-styleguide#42]
Hi John,

I'm not seeing the benefits of declaring 'ExampleCtrl as **vm**'. What is the intention by prefixing all template bindings with the same prefix, although their origin differs from each other ?

What do you think about declaring it semantically useful like 'ExampleCtrl as **example**' ? This way I can quickly identify the controller in use for the current html template just by looking at it. (Useful for example when maintaining multiple views and their respective controllers in multiple tabs).

**Comment by mikehuebner** [comment]
I don't mean to bring up another question, and I assume I'm having a blonde moment with this idea. But in the actual HTML for binding you should use `controllerAs: exVm` for one and `controllerAs: whoaVm` for another. Correct? You don't want all controllers to have vm as the alternate syntax because that can get confusing but in the JS itself you can use `var vm = this;` for each one?

**Comment by Markionium** [comment]
That is correct. In the html you would want to name them differently. Which means you won't have conflicts if you have the same property in both controllers for example.

However like you say in the controller itself that is not the case so then you can use `var vm = this;` in each of them. Which would be nice since then everything will look uniform. And in the html it is easy to identify which controller you are using by the different names.

**Comment by mikehuebner** [comment]
Awesome thanks for clearing that up!
And pertaining to directives... Should I even use the link function? There doesn't seem to be much of a reason besides the functionality of obtaining attributes, how would I get around this issue by using `controllerAs` in a  directive?

**Comment by chrisjlee** [comment]
This worth noting in the styleguide? regarding nested controllers and using controller as? I can provide the PR if needed,
