### ISSUE TITLE
Controller as with vm $scope.$watch syntax not working

### ISSUE THREAD

**Issue by akrawchyk** [johnpapa/angular-styleguide#428]
In the [Controller as with vm](https://github.com/johnpapa/angular-styleguide#controlleras-with-vm) section, the example for `$scope.$watch` looks like:

```
<input ng-model="vm.title"/>
```
```
function SomeController($scope, $log) {
    var vm = this;
    vm.title = 'Some Title';

    $scope.$watch('vm.title', function(current, original) {
        $log.info('vm.title was %s', original);
        $log.info('vm.title is now %s', current);
    });
}
```

However, this does not work for me in Angular 1.3.15. Instead, I have to pass a function to `$scope.$watch` that returns the value of the `vm` model:

```
<input ng-model="vm.title"/>
```
```
function SomeController($scope, $log) {
    var vm = this;
    vm.title = 'Some Title';

    $scope.$watch(function() {
        return vm.title;
    }, function(current, original) {
        $log.info('vm.title was %s', original);
        $log.info('vm.title is now %s', current);
    });
}
```

**Comment by Markionium** [comment]
I'm assuming that John would say this should be on SO ;)

The watch expression `vm.title` is evaluated against $scope. Your problem is likely that you did not use the `SomeController as vm` or the (`controllerAs` if it's a directive). This technically adds a `vm` property to the `$scope` object that refers to the controller. See below for working example.

http://jsbin.com/zasipoxara/edit?html,js,console,output

**Comment by akrawchyk** [comment]
@Markionium SO might have been a better medium for this but I was hoping to provide an adjustment for discussion in case this was in fact a bug in the styleguide :). I appreciate you taking the time to respond and provide an example :+1:

I believe I'm using the `controllerAs` syntax correctly (trivial example provided):

```
<section class="intro text-center" ng-controller="SubmissionController as submission">
    <button class="button" type="button"
        ng-disabled="submission.uploading"
        ngf-select ngf-accept="'image/*'" ng-model="submission.form.files" validator="required">
            Choose File
    </button>
</section>
```
```
function SubmissionController($scope, $validator) {
    var vm = this;
    vm.files = [];
    $scope.$watch('vm.uploading', function(new, old) {
        console.log(new, old);
    }
}
```

The difference for me is that I was watching a value for [ng-file-upload](https://github.com/danialfarid/ng-file-upload) so I'm not sure if that impacts the `$scope.$watch()` behavior.

**Comment by Markionium** [comment]
You're almost using it correctly. Like i mentioned before the `controllerAs` syntax kind of adds a property to the `$scope` that references that controller. So in your case that would be `SubmissionController as submission` and therefore the controller would be referenced by `$scope.submission`.

Since you created the watch as an angular expression that gets evaluated against that scope. `vm.form.files` would not exist as your controller property is `submission`. So therefore you would have to watch `submission.form.files` if you were to use `SubmissionController as submission`.

https://github.com/johnpapa/angular-styleguide#style-y032 does describe this, however perhaps it does not clearly enough mention that you would have to use `<controllerName> as vm` in order to be able to do $scope.$watch(`vm.<property>`)

**Comment by akrawchyk** [comment]
Thanks for clarifying!

**Comment by intellix** [comment]
Just had this very same issue. The explanation is very misleading if you're not sure how the internals are working.

It makes no reference to the controllerAs also being called `vm` and that being what you're actually watching. I think there should be some clarification like:
```js
    function config($stateProvider) {
        $stateProvider
            .state('home', {
                url: '/',
                templateUrl: 'home.html',
                controller: 'HomeController',
                controllerAs: 'home'
            });
    }

    function HomeController($scope) {

        var vm = this;
        vm.title = 'Some Title';

        $scope.$watch(function() {
            return vm.title;
        }, function(current, original) {
            $log.info('vm.title was %s', original);
            $log.info('vm.title is now %s', current);
        });

    }
```

**Comment by akrawchyk** [comment]
I believe if you try what @Markionium suggests, it should fix your issue. Since you used `controllerAs: 'home'`, try changing `var vm = this;` to `var home = this` in order to `$scope.$watch('home.title'...)`.
