### ISSUE TITLE
Add promises

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/angular-styleguide#43]
Style guide tips for using promises, both wrapped in angular services and using $q

**Comment by piernik** [comment]
1. How to handle multiple promises in resolve for routers? (usage of `$q.all`).
2. Getting params related data in router with resolve. Ex. in adding task view You have to fetch data from server (ex. name) related to custormer and ex worker of that customer (url like /tasks/add/?cutomer_id&worker_id).

**Comment by haroldcampbell** [comment]
Best ways to test code that use promises. I had a bit of issues finding this out when I was just learning.

**Comment by wardbell** [comment]
I wonder when a "style guide" ceases to be about style and becomes a "how to" instead.  The latter grows without end. Those looking for style become overwhelmed. Strunk & White's [Elements of Style](http://en.wikipedia.org/wiki/The_Elements_of_Style) was the greatest style guide of all time, in part because it was brief (just 52 pages).

@piernik - did you know that the resolve object is effectively one big `$q.all`? The route does not change into all of its promises are resolved. And the [Ng documentation for $q](https://docs.angularjs.org/api/ngRoute/provider/$routeProvider) answers your second question:

>Be aware that ngRoute.$routeParams will still refer to the previous route within these resolve functions. Use $route.current.params to access the new route parameters, instead.

@haroldcampbell - it seems to me that testing is its own topic. Testing *style* belongs here. But if John tried to cover testing patterns for Angular components this guide would never end.

I know I appreciate your questions so don't let me discourage you. But I think it is worth trying to keep in mind a balance between "style" and "how to".

My $0.02

**Comment by haroldcampbell** [comment]
All valid points @wardbell.

On Friday, February 6, 2015, Ward Bell <notifications@github.com> wrote:

> I wonder when a "style guide" ceases to be about style and becomes a "how
> to" instead. The latter grows without end. Those looking for style become
> overwhelmed. Strunk & White's Elements of Style
> <http://en.wikipedia.org/wiki/The_Elements_of_Style> was the greatest
> style guide of all time, in part because it was brief (just 52 pages).
>
> @piernik <https://github.com/piernik> - did you know that the resolve
> object is effectively one big $q.all? The route does not change into all
> of its promises are resolved. And the Ng documentation for $q
> <https://docs.angularjs.org/api/ngRoute/provider/%24routeProvider>
> answers your second question:
>
> Be aware that ngRoute.$routeParams will still refer to the previous route
> within these resolve functions. Use $route.current.params to access the new
> route parameters, instead.
>
> @haroldcampbell <https://github.com/haroldcampbell> - it seems to me that
> testing is its own topic. Testing *style* belongs here. But if John tried
> to cover testing patterns for Angular components this guide would never end.
>
> I know I appreciate your questions so don't let me discourage you. But I
> think it is worth trying to keep in mind a balance between "style" and "how
> to".
>
> My $0.02
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/johnpapa/angularjs-styleguide/issues/43#issuecomment-73161987>
> .
>


-- 
_________________________________
Harold Campbell
Cell: +27-76-825-2315 (c)

**Comment by johnpapa** [comment]
there are a few things about promises in the guide now. i'm going to close this one unless a specific new case is requested.
