### ISSUE TITLE
Event array for easy deregistration during $destroy

### ISSUE THREAD

**Issue by juristr** [johnpapa/angular-styleguide#434]
Hi,

in a code sample I've seen a strategy where the author pushed all of the registered events onto an array for then being able to de-register them easily during `$destroy`. Like

```javascript
var unregisterEvents = [];
...

unregisterEvents.push($rootScope.$on('...', function(){

});

unregisterEvents.push($rootScope.$on('...', function(){

});


$scope.$on('$destroy', function(..){
  // unregister all events
  for (var i=0, i< ....) {
     unregisterEvents[i]();
  }
});
```

What's your opinion on that?

**Comment by dietergeerts** [comment]
I use events sparingly, but when I use them I do:
```
$scope.$on('$destroy', $scope.$on('...', function () {}));
```

**Comment by juristr** [comment]
@dietergeerts Ok, that's another interesting approach

**Comment by gkalpak** [comment]
@dietergeerts, actually there is no need to deregister controllers on `$scope` when `$scope` is being destroyed.

**Comment by juristr** [comment]
@gkalpak But there is for directives, right?

**Comment by gkalpak** [comment]
@juristr, not sure what you mean by _"for directives"_.

--
**EDIT:**
I just realized that in my previous comment I said _"controllers"_ instead of _"listeners"_.
Maybe it caused confusion (I corrected it).

--
The point is, you don't need to deregister listeners that are registered on scope X when scope X gets destroyed (because Angular will take care of that).
What you _do_ need to do when scope X is being destroyed, is deregister listeners that are registered on _other_ scopes that will leave on.

E.g.:

```js
var deregister1 = $scope.$on(...);
var deregister2 = $rootScope.$on(...);

$scope.$on('$destroy', function () {
  // deregister1();   // <-- No need to deregister 
  deregister2();      // <-- Need to deregister
});
```

**Comment by tmcgee123** [comment]
Is there any type of standard to this? Are there pros to registering on $rootScope vs child $scopes? The [Angular FAQ's](https://docs.angularjs.org/misc/faq) say to stay away from $rootScope usage as much as possible. We use both approaches in our project, but it is a highly debated subject.

**Comment by gkalpak** [comment]
@tmcgee123, I don't think there is any standard, so it's more of a matter of preference.

Generally, it's a good idea (imo) to avoid using `$rootScope` whenever you can.
Some people suggest listeneing for events on `$rootScope` (instead of listening for them on the child scopes) as a performance optimization, but in most apps the gain is negligible (but the maintanance/clean-up cost often isn't).

**Comment by johnpapa** [comment]
better for SO
