### ISSUE TITLE
Cleaning up watches

### ISSUE THREAD

**Issue by alexlrobertson** [johnpapa/angular-styleguide#437]
Is there a preferred way to clean up after `$on` and `$watch`?

I prefer this concise way:

```javascript
$scope.$on('$destroy', $scope.$watch('foo', doSomething));
```

Assigning to a variable is clearer, but clunkier:

```javascript
var destroyWatchFoo = $scope.$watch('foo', doSomething);

$scope.$on('$destroy', destroyWatchFoo);
```

**Comment by gustavohenke** [comment]
Isn't this done automatically?

**Comment by alexlrobertson** [comment]
Not for `$rootScope`.

I know that there's a recommendation to put `$rootScope` watches in services, but they should still be cleaned up, right?

**Comment by gkalpak** [comment]
Yeah, you don't need to unregister listeners that are registered on the very scope that is being destroyed.
Note that in certain cases, you might need to use `$element.on('$destroy', unregisterStuff)` instead (e.g. on an directive with `scope: false` that sets up some listeners on the scope).

Unregistering listeners that are set up in services shouldn't be necessary (unless you are doing some crazy stuff), since service instances are singletons.
