### ISSUE TITLE
Y230: Why are "unused", "strict", and "esnext" set to false"?

### ISSUE THREAD

**Issue by AleksueiR** [johnpapa/angular-styleguide#438]
Hi,

I was wondering why **unused**, **strict** and **esnext** are set to **false** in jshint options, [Y230](https://github.com/johnpapa/angular-styleguide#style-y230). They seem like good options to keep turned on.
Is there a particular reason for these settings?

Thank you.

**Comment by stefan-schweiger** [comment]
I think `unused: true` is a bit much, I like it better just using `unused: "vars"` because when writing code like this:

scope.$watch('vm.value', function(newValue, oldValue) {
    data.value = newValue;
                        
    setValues(data);
});

It's still a good reminder that you also could use `oldValue` if you decide to change something in the function.

But I also can see that `unused: false` can have it's pros as I often implement something I want to use in the future, but currently only is a empty construct and I don't want the style checks to fail because of such things.

**Comment by johnpapa** [comment]
you can certainly tinker with the settings, but these are a good balance of useful and not annoying.
