### ISSUE TITLE
Where to put CSS / Sass / Less ? -  by component or separate ?

### ISSUE THREAD

**Issue by raDiesle** [johnpapa/angular-styleguide#480]
Hi everybody,

https://github.com/johnpapa/angular-styleguide#style-y152
Is not mentioning where to put CSS.

What is the preferred way nowadays : by component or in a separate rootFolder or project ?

**Comment by Jandalf** [comment]
I put the CSS files to the components, so I can easily see where a css class is used. you just need something to concat all style files together, so you only need to import one file in your html.

**Comment by dietergeerts** [comment]
We have a separate project to create the toolkit we use for our AngularJS Apps. Made with Fabricator, great tool, and great way of working. You have to think of your style/css in a whole different way, resulting in a better styling.

**Comment by johnpapa** [comment]
CSS goes best with the thing it will be distributed with. If that be a component that gets modularized and thrown into a bower component, then thats a good place.

Putting CSS in each folder where a component lives helps keep that CSS localized. But if that component will not be made modular on its own and installable (i.e. via bower) then it might as well share CSS with what component is being distributed.

It gets a bit involved ... but a general rule of thumb is not to put CSS all in one place because it is hard to modularize. Instead, put CSS at whatever level will be made into a component.
