### ISSUE TITLE
Is any difference in defining controllerAs syntax

### ISSUE THREAD

**Issue by fetis** [johnpapa/angular-styleguide#582]
Hi all.
Angular  introduced `as` word support directly in `controller` property.

So, now you can specify controller name either
```
controller: 'MyControllerName as vm'
```
or
```
controller: MyCntrollerFunc,
controllerAs: 'vm'
```
Is any difference between this 2 methods in terms of performance, parsing etc?

**Comment by zachlysobey** [comment]
Well, one difference is you have to register a controller on your module to use the `'ControllerString as vm'` syntax. Thus, when inlining a directive controller (as suggested in this style-guide) you must use `controllerAs`.

I imagine there might be a small amount of overhead with the former method, due to actually parsing the string and registering the controller, buy I'm certain any performance impact would be negligible.

**Comment by dietergeerts** [comment]
The first is shorter and more readable. I always use it.

**Comment by johnpapa** [comment]
answered above
