### ISSUE TITLE
Refresh Data in ng-repeat

### ISSUE THREAD

**Issue by jlien-calwater** [johnpapa/angular-styleguide#593]
Hi, I've been following this guide to the dot.

One of my issue I came across is refreshing/updating data in a ng-repeat on IE. All other browser refresh find when a new data set is being returned from $http factory, but just not IE. I've already added cache busting for IE, but the view (vm) does not get updated.

I've seen [fixes](http://stackoverflow.com/questions/15475601/angularjs-ng-repeat-list-is-not-updated-when-a-model-element-is-spliced-from-t) that suggest using $scope.$apply(); but that is not possible if you are binding var vm = this;.

Is there a better solution to this or do I need to revert back to $scope just to resolve this issue?

**Comment by zachlysobey** [comment]
Not exactly sure what your issue is. Maybe with a bit more info... (and maybe this is better suited for StackOverflow?)

For starters `$scope.$apply()` has no relation to `controlerAs or `vm = this`. You *can* still inject `$scope` and use `$scope.$apply()`.

Other useful info would be perhaps a code example (a plunkr ideally) and your version of IE, etc...

**Comment by dietergeerts** [comment]
I think there is another problem. If you just have bind the list to the ng-repeat, Angular should see the changes. There is no difference in browsers here. So it will be some other thing that's wrong. Post some code snippits, maybe we can see the reason?
