### ISSUE TITLE
Where to call service initialization logic?

### ISSUE THREAD

**Issue by jfache** [johnpapa/angular-styleguide#594]
Hi there,

Let's say that I have some initialization logic into one of my services and that I isolated that logic into an `init` function.

Should I call that `init` function from within the service? (similar to what is recommended for controllers https://github.com/johnpapa/angular-styleguide#controller-activation-promises)

Or should I call that `init` function from my app run block? (as per https://github.com/johnpapa/angular-styleguide#run-blocks)

Thanks a lot for your input

**Comment by dietergeerts** [comment]
Depends. If it doesn't block other things than only your service, then put it into your service. If it's blocking some things, then put it into your run block. For example, I need to wait for my translations to load, thus the init of them is been put into my run block. I also need to have some feedback on a question call in order to know which module the user should be brought to, so that's also some init call that's done in the run block.

General rule: if it's not blocking for other things ( also indirectly), and only for your service, then put it into your service, it then belongs there. Otherwise, put it into your service, but call it from your run block, so your run block knows when it's done to proceed....

**Comment by jfache** [comment]
@dietergeerts That's a great rule of thumb, thank you!

**Comment by johnpapa** [comment]
run blocks can be tough to test. init functions can be tough too. i try to avoid startup logic, when possible, and its not always possible.

so it depends on your perspective. first its good to look at why you need to run code when it starts your service. if you need translation files, another option is to run it in the service and set a flag in the service that tells its functions when it is "ready".

another option is to run the logic for getting initial data in manual bootstrap phase. another is to send the data across from the initial static page load. both of these allow the data to come before angular is ready, and thus you can inject the data into the service and avoid that call

there is no silver bullet here. :)

**Comment by johnpapa** [comment]
closing as there is no perfect answer here.
