### ISSUE TITLE
Should we remove references to bower and reccomend NPM?

### ISSUE THREAD

**Issue by zachlysobey** [johnpapa/angular-styleguide#617]
There are a few references to `bower_components` but no real mention of front-end dependency management.

Any interest in a PR adding a passage recommending NPM for all dependency management and removing these `bower` references?

Similar issue: https://github.com/johnpapa/angular-styleguide/issues/609

**Comment by attilacsanyi** [comment]
Imho it is good to keep here as there are some libs which are not available in npm for example specific ui lib like angular ui calendar. As bower_dependencies have already integrated properly with gulp here this is a great guide how to do it properly covering both npm and bower dependency management.

**Comment by zachlysobey** [comment]
Personally I don't think that is a valid reason to keep bower. You do not need a library to be registered in NPM to use it with npm either, it works perfectly pointed at a branch or tag of a github repository.

Here's a tweet from a guy on the bower team: https://twitter.com/desandro/status/667417324123774976

> moving to npm is right thing to do. I want to get to a state where that's an easy transition

Bower is not bad, and perhaps its worth keeping stuff in, but I'm pretty confident that we should be nudging people in the direction of NPM if anything.

Not really sure what you mean with your last sentence... is there something here covering dependency management? B/c I just saw a few sporadic references to `bower_components` without actually covering either bower or npm.

**Comment by johnpapa** [comment]
Bower is fine for now ... worht keeping an eye on for now

**Comment by zachlysobey** [comment]
Fair enough. Thanks for weighing in @johnpapa.

**Comment by dietergeerts** [comment]
I personally don't use Bower anymore, but some modules are only available in bower, and you don't have to expose that, because you can control it through npm, so who's working with your repo will not know this.

**Comment by attilacsanyi** [comment]
Nice guys,  any example how to use this through npm only,  for example angular ui calendar?

**Comment by zachlysobey** [comment]
Checkout https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

so it would be something like this perhaps (untested)

> git://github.com/angular-ui/ui-calendar.git#0.9.0-beta.1

**Comment by dietergeerts** [comment]
@attilacsanyi, just add bower as a dependency in your package.json file, then add 'bower install' to your scripts in package.json, so you only need to use npm commands from then on. Off course you still have to set the bower dependencies initially, and reference their files you need in your gulp file, but other than that, 'the user of the project doesn't need to know that....

**Comment by attilacsanyi** [comment]
Nice thanks guys!

**Comment by antonybudianto** [comment]
I personally use bower for front-end dependencies since it's easy to copy fonts, get css/js files then concat & minify/uglify it. 
How do I get the `main` files with npm ? so I can copy the fonts, and inject css and js files to index.html.

**Comment by zachlysobey** [comment]
@antonybudianto Not really sure what you mean? It's generally the same idea as bower but instead of `bower_components` look in `node_modules`.

There are plenty of references on the internet for using npm for front-end dependencies.

A couple results from a quick search:

 - https://medium.com/@nickheiner/why-my-team-uses-npm-instead-of-bower-eecfe1b9afcb#.jcqp4tde8
 - https://gofore.com/ohjelmistokehitys/stop-using-bower/

**Comment by antonybudianto** [comment]
@zachlysobey : Thanks. But most of the front-end package example is javascript packages, what to do about package like `font-awesome`? I don't want to manually copy the font/css files.

**Comment by bradchesney79** [comment]
npm in conjunction with gulp/grunt should be able to do all the things bower does-- I recently removed it from my stack because it really is unnecessary. curl nvm, nvm install v[X.X.X], npm init, npm install npm [packages] --save (adds packages to package.json), npm install [packages] --save-dev (adds packages to package.json), (alternatively, if you already have the package.json: npm install). Other more advanced shenanigans to get stuff installed can be done at the npm step.

Then you get into the task runner part. You have pulled in all the packages you need to make your server create the front end resources workflow. Let's use gulp as the task runner for instance. gulp can instantiate a 'watch'. That watch sits watches for changes in specified files, usually js, json, and directory contents. (Captain Obvious says don't do drugs.) When a change is detected, the front end build workflow process is kicked off as needed. Missing third-party assets (i.e. fonts) are placed where they need to go, SASS is concatenated & processed into CSS, the generated CSS is placed where it needs to go, JS is concatenated & minified, the generated JS is placed where it needs to go, and the test runner is called.

Let's use karma, jshint is run on the whole shebang, then the unit tests are run as specified. Last, I clean up after my install by removing unnecessary things. And bob's your uncle-- you have a tested website. What is bower doing for you that this workflow isn't?

This is all on a dev server. A very large .gitignore allows the most recent website build to be requested without the unneeded files (git add . is not used...). That creates a branch/commit that the qa or prod server can be updated from.

**Comment by antonybudianto** [comment]
Actually without Bower, it's still okay, and it's the best when it comes to javascript packages (lodash, jquery...), but when it comes to package like `font-awesome`, npm becomes hopeless since the `package.json` doesn't list the main files, like `bower.json` does, but it's still okay, I can create gulp task to copy the fonts when bundling, where with `main-bower-files`, it's done nicely. 
Thank you for suggestion, I'm planning to migrate front-end dep to npm soon too.

**Comment by zachlysobey** [comment]
@antonybudianto I get it now. In my current workflow, I do what you are saying, the tedious hardcoding of paths that my build will then copy over to my dist/ directory.

I'm not too knowledgable on this topic, but `package.json` *does* provide an *entrypoint*, and perhaps other mechanisms for finding relevant files(?). I know some tools like webpack, and rollup.js make it so you can *require* most npm dependencies (even css, img, etc...) and it just works. I've only spent a short while with such tools, but pretty sure they could make this workflow a bit better.

**Comment by antonybudianto** [comment]
@zachlysobey : For now, I prefer jspm, they got promising [plugins](https://github.com/jspm/jspm-cli/blob/master/docs/plugins.md)

**Comment by zachlysobey** [comment]
yea, haven't yet played with that but I hear good things. Too much front-end tech, too little time ;-(

**Comment by mikeerickson** [comment]
I am completely on board with this movement, and have already done so myself.  But sharing this resource with others (including newbs and colleagues) it would be a positive move to direct them to use npm as well.
