### ISSUE TITLE
Unit test and e2e test

### ISSUE THREAD

**Issue by brutalcrozt** [johnpapa/angular-styleguide#645]
as long i follow this guide i feel avoid many problem.
I'd like to propose to extend the guide to testing, i have got many problem since entering unit test and i just got few information from this guide. I feel really confuse when i didn't know much about testing and recently when i read more about unit testing some of them say the that thing should done on e2e testing. I just hope that more experience programmer can give some advice about unit test and e2e testing so newcomer can avoid unnecessary mistake.
I just got my first test fail, and i had 8 dependency on my controller test. :worried:

**Comment by angellicacardozo** [comment]
Hello @brutalcrozt. I do agree with you but I think it will take some time to have some test pattern specified and then documented. I have been writing simple tests with this style guide (still working). You can see it in my repository: https://github.com/angellicacardozo/jasmine-angular-todolist

Hope it helps you in you first step.

**Comment by MarcLoupias** [comment]
Check [ng-describe] (https://github.com/kensho/ng-describe), it is a must have in an AngularJs project.

**Comment by zachlysobey** [comment]
A good resource for e2e (protractor) tests:
https://github.com/CarmenPopoviciu/protractor-styleguide

**Comment by brutalcrozt** [comment]
Thanks guys, i really new on testing. I have read some of them (i skip e2e for now).
But i still confuse how to inject or mock my dependencies which use `ui-router.resolve`

**Comment by MarcLoupias** [comment]
Delegate logic in the resolve to a

**Comment by philn5d** [comment]
Sort of new to angular. I generally have an issue with e2e testing style I've seen for it. Especially jasmine tests. Usually they're something like it("should have a controller"... To me that's defining too much implementation details. I prefer a style more like it("should show all of the avengers" ... But here we have a problem since there is no avengers given to show. Even better would be - given("the following avengers", [...,...] ... when("user visits avengers page" ... it("should show all avengers" ... it("should show avenger name, super power, home planet, food preference, ..."). I know these are not jasmine functions, but the style is what I like better than what I've seen in all demos and tutorials so far.

**Comment by johnpapa** [comment]
better for SO
