### ISSUE TITLE
$watch from example with "controller as" syntax not working

### ISSUE THREAD

**Issue by RealJTG** [johnpapa/angular-styleguide#666]
https://github.com/johnpapa/angular-styleguide#style-y032

```javascript
    $scope.$watch('vm.title', function(current, original) {
        $log.info('vm.title was %s', original);
        $log.info('vm.title is now %s', current);
    });
```

While this appears to be a trivial synthetic example, `$scope.$watch('vm.username', function() {...})` simply not working for me (according to docs it should).

But it works with function call like this

```javascript
    $scope.$watch(function (){return vm.username;}, function (current, original) {
        ...
    });
```
What's actually happening here?
Example http://plnkr.co/edit/XXWqT5we26o1jgwxdjuV?p=preview

**Comment by EricDeCoff** [comment]
First off your example is a string....

2nd example is a function that returns string

**Comment by gkalpak** [comment]
When using the srting version, the expression is parsed and the resulting function tries to access `$scope.vm.username`. But in your template, you are using `... as ctrl`, so the controller is aliased on `$scope` as `ctrl` not `vm`.

That's why it is not a good idea (imo at least), to use the string version, because it couples the implementation and the consumption of the controller. I.e. at the time you define your controller, you don't know where it's going to be used and how the consumer of the controller will choose to alias it (e.g. there might be other controllers aliased as `vm` that the template needs access to and your controller has to be aliased as something else).

It's always safer to use the function version.

**Comment by RealJTG** [comment]
@gkalpak oh I see, kinda unobvious. Thanks.
