### ISSUE TITLE
To which version of Angular does this apply?

### ISSUE THREAD

**Issue by NevillePerkins** [johnpapa/angular-styleguide#681]
I dive in and out of AJS every for few months so typically whenever I start another AJS project it is about 3 or 4 versions later than the last project I did. At one point there was a big shift in the way controllers have to be defined and then some people do everything inline and others use $inject. And now the whole IIFE thing? That really makes for ugly code adding whole extra level of indentation. Is this really necessary? 

The sample project I downloaded from here uses v1.2 but am starting a new project with AJS v1.5. 
Are all these style guides still appropriate for AJS 1.5+? 

Thanks in advance.

**Comment by brutalcrozt** [comment]
IMO the impact is on code readability, application structure. Since all of them will be 1 file and minified.

> The sample project I downloaded from here uses v1.2 but am starting a new project with AJS v1.5. 
Are all these style guides still appropriate for AJS 1.5+?

[style guide a1](https://github.com/johnpapa/angular-styleguide/tree/master/a1/README.md) for major v1.x.x

[style guide a2](https://github.com/johnpapa/angular-styleguide/tree/master/a2/README.md) for major v2.x.x

at this time angular v.2 is still beta, the style guide also still draft.

**Comment by zachlysobey** [comment]
The use of IIFEs is defended in the relevant section of the styleguide:
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#iife You can probably do without it if it really bothers you (though I wouldn't), or perhaps find a solution that allows use of es6 modules -- which give you all the benefits of the IIFEs.

This guide is definitely still relevant in 1.5+. It doesn't (yet?) touch on the new `module.component` helper released in 1.5 though.

> there was a big shift in the way controllers have to be defined

Controller definitions from 1.0 still work in 1.5 AFAIK. There is some stuff that was *added* like controllerAs, bindToController, etc... and these are all discussed in the styleguide.

> some people do everything inline and others use $inject

There are multiple approaches to this. This style-guide prefers the `$inject` syntax preferably done with some tooling rather than just typed out in-line.

**Comment by NevillePerkins** [comment]
Thank you Zach for the feedback and confirmation that this is still good for 1.5. 

On a side note, what do you mean by " the $inject syntax preferably done with some tooling rather than just typed out in-line"? 

I'm old school and prefer writing my own code. By "tooling" I'm guessing you mean some sort of code-generator? The control freak in me just battles with that conceptually.

**Comment by zachlysobey** [comment]
the tooling (ng-annotate) is described here

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#minification-and-annotation

If you're not into build steps or code generation, then its probably not for you. Me? I would hate having to type out all the things I'm injecting twice.

**Comment by NevillePerkins** [comment]
Thanks Zach!
