### ISSUE TITLE
JavaScript Closure should be renamed just IIFE, because Closure and IIFE are two separate things.

### ISSUE THREAD

**Issue by jianlin** [johnpapa/angular-styleguide#700]
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y010

It mentions JavaScript Closures and IIFE.  But using IIFE to create a local scope to prevent leak out to the global space has nothing to do with closures.

In C language, there is no closure, but we can use the same or similar technique just like IIFE to create a local scope and create variables that won't leak to the global space.  So closures and IIFE are different concepts.  What is being used is IIFE.   Closure, it doesn't really matter if it exist or not in this case.  It will be better if we use and propagate the correct concept around.

**Comment by MAustinMMDP** [comment]
Maybe in C there is no closure but in JavaScript "An IIFE is often used to create scope to encapsulate modules. Within the module there is a private scope that is self-contained and safe from unwanted or accidental modification. This technique, called the module pattern, is a powerful example of using closures to manage scope".

http://www.sitepoint.com/demystifying-javascript-closures-callbacks-iifes/

**Comment by jianlin** [comment]
that is incorrect concept.  Isolating local variable inside of a local scope is IIFE and has nothing to do with a closure at all.

**Comment by gkalpak** [comment]
I (sort of) agree with @jianlin here. There is typically no closures involved in registering an Angular service/controller/filter/directive/etc inside an IIFE (as suggested in this guide). 

--
> An IIFE is often used to create scope to encapsulate modules

@MAustinMMDP, because it _"is ofter used"_, it doesn't mean it is used _every time_.
Angular has it's own module system, so (as far as I understand this styleguide) IIFEs are not used as a means to encapsulate modules, but as a way to isolate local variables (e.g. a function declarations) from the global context.

In that sense, the quote from http://www.sitepoint.com/demystifying-javascript-closures-callbacks-iifes/ is correct (in general) but irrelevant (in this particular case).

**Comment by jianlin** [comment]
actually the line on SitePoint really should say something like:

> An IIFE is often used to create scope to encapsulate modules. Within the module there is a private scope that is self-contained and safe from unwanted or accidental modification. This technique, called the module pattern, is a powerful example of using **[local scope, or a function with local scope, or simply, a function]** to manage scope, and it’s heavily used in many of the modern JavaScript libraries

**Comment by MAustinMMDP** [comment]
I would need @johnpapa to confirm but I believe it is largely used in this styleguide for a module/design pattern, which is a preferred practice in the JavaScript community, as well as for when your code is minified and bundled into a single file for deployment to a production server, you could have collisions of variables and many global variables. An IIFE protects you against both of these by providing variable scope for each file.

**Comment by johnpapa** [comment]
It should just say "Scope"
