### ISSUE TITLE
Loading services at bootstrap or main component?

### ISSUE THREAD

**Issue by Foxandxss** [johnpapa/angular-styleguide#702]
Something like:

```
@Component({
  selector: 'my-app',
  template: `Foo`,
  providers: [ROUTER_PROVIDERS, LoginService]
})
export class AppComponent { }
```

vs

```
bootstrap(AppComponent, [ROUTER_PROVIDERS, LoginService]
```

**Comment by johnpapa** [comment]
Good question. We had a lot of chats on this. The highest comp level that is needed. Not at bootstrap.

Comp need services. Not bootstrap. This also makes it much easier to test since the comp knows which services it needs. 

Bootstrap is very short. Then when I test the comp has everything it needs. It was Misko who first drive this idea with me and Ward. I agree with it and it has helped me think more about he components and less about bootstrap. The root app component becomes more important as it should. It has what it needs. Then if we bootstrap for mobile instead of browser the bootstrap changes but the components will not. Which is much cleaner

Anyway. I need to write this up in more detail in the guide. :)

thanks for the issue

**Comment by kazemihabib** [comment]
Is it good idea to load all services we need in the main component.
Fore example main ---> A-->B-->C and I need a service just in C component what which one is bettere 
1-load it in main component 2-load it in C component?

**Comment by bampakoa** [comment]
It is better to load it in the C component, since that component will only need it. There is no point of A and B to know about the service since they will never use it.
Please note that If you load it in the C component it will be directly available to all children components of the C component.

**Comment by anisdjer** [comment]
Hello

Sometimes, I need to inject services in developping mode and not in the production mode, therefore I think injecting them in bootstrap function is more adequat.

But in general cases, injecting services in the component is better.

**Comment by johnpapa** [comment]
Angular 2 issues will now go to the A2 style guide in the angular.io repo
