### ISSUE TITLE
Vendor globals: constant vs factory

### ISSUE THREAD

**Issue by trumbitta** [johnpapa/angular-styleguide#746]
Ref: https://github.com/johnpapa/angular-styleguide/blame/master/a1/README.md#L2922

[I always used a factory / service](https://github.com/ngTrumbitta/ngtrumbitta-services-lodash/blob/master/src/lodash.service.js) to get an injectable third-party util like lodash or moment into my Angular applications.  
Using a constant seems a nice thing to do, but I can't figure out which approach is better and why.

Care to elaborate on the differences?

**Comment by bampakoa** [comment]
@trumbitta I am also defining constants for 3rd party libraries because I use them as is. If I want to extend the behavior of the library (like [this](https://github.com/johnpapa/generator-hottowel/blob/master/app/templates/src/client/app/blocks/logger/logger.js) logger that extends toastr), then I would definitely create a service.

**Comment by johnpapa** [comment]
i dont think it matters much either way. I just choose constant as it feels better. but a factory is fine.
