### ISSUE TITLE
Best way for required directive attribute

### ISSUE THREAD

**Issue by amiceli** [johnpapa/angular-styleguide#836]
For example, I've following directive : 

    (function () {
    
        angular.module('app').directive('customInput', customInput);
    
        customInput.$inject = [];
    
        function customInput() {
            return {
                restrict    : 'E',
                template    : 'templates/customInput.html',
                link        : link,
                controller  : 'customInputController',
                controllerAs: 'customInCtrl',
                scope       : {
                    'model': '='
                }
            };
    
            function link(scope, el, attrs) {
                scope.forLabel = attrs.forlabel || 123456; // how to check forLabel
            }
        }
    })();

What is best way to prevent null value for a directive attribute ? 

Set a default value or throw an error ? (Or something else)

Thanks.

**Comment by MarcLoupias** [comment]
It fully depends on the business rules.

If the rule is : "When the value is null, set default value", you must not throw an error because your application should set a default value and continue to run.

For example, if your app business is to sell products, and in the order form you can choose a color for the product, you could have a default value for the color. You should not fail the form submit if the user have not chosen a color but set one by default.

If the rule is : "The value is mandatory, if it is null the app should fail", you must throw an error and must not be able to continue the action the user.

Same example as above, you should not be able to submit your order form without a delivery address (impossible to set a value by default).

**Comment by amiceli** [comment]
Ok, thank for your explanations. It's clearer now.
