### ISSUE TITLE
$resource

### ISSUE THREAD

**Issue by tabdurman** [johnpapa/angular-styleguide#86]
No word on using $resource! They made it easy to access repositories, but we heard nothing about that!

**Comment by sylvain-brouillat** [comment]
Opening an old post, I hope you would respond anyway.
Using $resource as data service may lead to style questions. 

The easy way (convention ?) to use $resource is to define one factory by resource URI, for instance : 
```
  .factory('Dashboards', ['$resource', function ($resource) {
    return $resource('/dashboards/:id');
  }])
...
  .factory('Users', ['$resource', function ($resource) {
    return $resource('/users/:id');
  }])
```
creating the following files : 
dashboards.factory.js
users.factory.js

In your styleguide, you recommend to put data services in a single service "data.service.js". Does it still apply if I use the "$resource as data service" style ?
**If not : **
What is the naming (service and file name) to choose to distinguish a "Dashboards" service that encapsulate the business logic part of the "DashboardsController" and the "Dashboards" data service ?

**Comment by ruionwriting** [comment]
@sylvain-brouillat in my case I've decided to have all my data services on a 'data' module and for each context I have *<context>.dataservice.js*. The reason I do this is because each context contains a lot of operations and feels more cleaner to separate them. Does this naming sounds good to you?

Also this makes all my jasmine tests a lot more organized and clear. Basically I fallow the same logical tree to organize them.
